package com.jjj.crm.settings.mapper;

import com.jjj.crm.settings.pojo.DicValue;
import com.jjj.crm.settings.pojo.DicValueExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.MapKey;
import org.apache.ibatis.annotations.Param;

public interface DicValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Fri Oct 14 00:14:48 CST 2022
     */
    int countByExample(DicValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Fri Oct 14 00:14:48 CST 2022
     */
    int deleteByExample(DicValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Fri Oct 14 00:14:48 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Fri Oct 14 00:14:48 CST 2022
     */
    int insert(DicValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Fri Oct 14 00:14:48 CST 2022
     */
    int insertSelective(DicValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Fri Oct 14 00:14:48 CST 2022
     */
    List<DicValue> selectByExample(DicValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Fri Oct 14 00:14:48 CST 2022
     */
    DicValue selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Fri Oct 14 00:14:48 CST 2022
     */
    int updateByExampleSelective(@Param("record") DicValue record, @Param("example") DicValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Fri Oct 14 00:14:48 CST 2022
     */
    int updateByExample(@Param("record") DicValue record, @Param("example") DicValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Fri Oct 14 00:14:48 CST 2022
     */
    int updateByPrimaryKeySelective(DicValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Fri Oct 14 00:14:48 CST 2022
     */
    int updateByPrimaryKey(DicValue record);

    /**
     * 查询线索列表所需要的数据字典
     * @param typeCode
     * @return
     */
    // making for myself
    List<DicValue> selectClueDicByTypeCodes(String typeCode);

}